apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: packages-config
    options:
      disableNameSuffixHash: true
    files:
      - delivery.yaml
      - packages.yaml.tmpl
      - offline-packages.yaml.tmpl
